name: Build debian package
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build DEB Package
        run: make deb
        env:
          METALBOND_VERSION: "${{ inputs.version }}"

      - name: Upload for next actions job
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: metalbond_${{ inputs.version }}_${{ matrix.architecture }}
          path: ./target/metalbond_${{ inputs.version }}_${{ matrix.architecture }}.deb
