name: Build and Release MetalBond
on:
  release:
    types:
      - published
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build DEB Package
        run: make deb
        env:
          METALBOND_VERSION: ${{ github.ref_name }}

      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref_name
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)

      - name: Upload Release Asset
        id: upload-release-asset-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/metalbond_${{ steps.set_version.outputs.no-v }}-amd64.deb
          asset_name: metalbond_${{ steps.set_version.outputs.no-v }}-amd64.deb
          asset_content_type: application/x-deb

      - name: Upload Release Asset
        id: upload-release-asset-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/metalbond_${{ steps.set_version.outputs.no-v }}-arm64.deb
          asset_name: metalbond_${{ steps.set_version.outputs.no-v }}-arm64.deb
          asset_content_type: application/x-deb
          