name: Create source tarball
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: create tarball
        run: make tarball
        env:
          METALBOND_VERSION: "${{ inputs.version }}"

      - name: Upload for next actions job
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: metalbond-${{ inputs.version }}.tarball
          path: ./target/metalbond_${{ inputs.version }}.orig.tar.gz
