name: upload to garden linux repo
on:
  workflow_call:
    inputs:
      version:
        type: string
    secrets:
      GITLAB_DEPLOY_KEY:
      GITLAB_KNOWN_HOSTS:
jobs:
  build:
    runs-on: self-hosted
    steps:
      
      - uses: actions/download-artifact@v2
        with:
          name: metalbond-${{ inputs.version }}.tarball

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh
          cat << EOF >> ~/.ssh/gitlab_key
          ${{ secrets.GITLAB_DEPLOY_KEY }}
          EOF
          cat << EOF >> ~/.ssh/known_hosts
          ${{ secrets.GITLAB_KNOWN_HOSTS }}
          sudo chmod 600 ~/.ssh/gitlab_key
          cat << EOF >> ~/.ssh/config
          Host gitlab.com
          HostName gitlab.com
          IdentityFile ~/.ssh/gitlab_key
          EOF

      - name: upload tarball to pristine-lfs
        run: |
          echo "deb http://deb.debian.org/debian/ bookworm main contrib non-free" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update -qy 
          sudo apt-get install -qy --no-install-recommends pristine-lfs
          sudo chmod 600 ~/.ssh/gitlab_key
          git config --global user.email "contact@gardenlinux.io"
          git config --global user.name "GitHub Actions"
          eval `ssh-agent -s`
          ssh-add ~/.ssh/gitlab_key
          git clone git@gitlab.com:gardenlinux/gardenlinux-metalbond.git
          cd gardenlinux-metalbond
          cp ../metalbond-${{ inputs.version }}.orig.tar.gz .
          pristine-lfs commit --force-overwrite metalbond-${{ inputs.version }}.orig.tar.gz
          git push origin pristine-lfs











