name: upload to garden linux repo
on:
  workflow_call:
    inputs:
      version:
        type: string
    secrets:
      GITLAB_DEPLOY_KEY:
      GITLAB_KNOWN_HOSTS:
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix: 
        architecture: [ amd64, arm64 ]
    steps:
      
      - uses: actions/download-artifact@v2
        with:
          name: metalbond_${{ inputs.version }}_${{ matrix.architecture }}

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh
          cat << EOF >> ~/.ssh/gitlab_key
          ${{ secrets.GITLAB_DEPLOY_KEY }}
          EOF
          cat << EOF >> ~/.ssh/known_hosts
          ${{ secrets.GITLAB_KNOWN_HOSTS }}
          sudo chmod 600 ~/.ssh/gitlab_key
          cat << EOF >> ~/.ssh/config
          Host gitlab.com
          HostName gitlab.com
          IdentityFile ~/.ssh/gitlab_key
          EOF

      - name: clone gitlab lfs-storage
        run: |
          sudo chmod 600 ~/.ssh/gitlab_key
          git config --global user.email "contact@gardenlinux.io"
          git config --global user.name "GitHub Actions"
          eval `ssh-agent -s`
          ssh-add ~/.ssh/gitlab_key
          git clone -b lfs-storage git@gitlab.com:gardenlinux/gardenlinux-metalbond.git
          cd gardenlinux-metalbond
          git lfs install
          cp ../metalbond_${{ inputs.version }}_${{ matrix.architecture }}.deb .
          git add metalbond_${{ inputs.version }}_${{ matrix.architecture }}.deb
          git commit -am "GitHub: metalbond ${{ inputs.version }} ${{ matrix.architecture }}"
          git push origin lfs-storage











