name: upload to garden linux repo
on:
  workflow_call:
    inputs:
      version:
        type: string
    secrets:
      GITLAB_DEPLOY_KEY:
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix: 
        architecture: [ amd64, arm64 ]
    steps:
      
      - uses: actions/download-artifact@v2
        with:
          name: metalbond_${{ inputs.version }}_${{ matrix.architecture }}

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan gitlab.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.GITLAB_DEPLOY_KEY}}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions

      - name: clone gitlab lfs-storage
        run: |
          git clone -b lfs-storage https://gitlab.com/gardenlinux/gardenlinux-metalbond

      - name: upload to gitlab lfs-storage
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: | 
          git add metalbond_${{ inputs.version }}_${{ matrix.architecture }}.deb
          git commit -am "GitHub: metalbond ${{ inputs.version }} ${{ matrix.architecture }}"
          git push origin master











