name: Build and Publish Docker Image

on:
  release:
    types:
    - published
  push:
    branches:
    - master
    tags:
    - v*
    paths-ignore:
    - 'docs/**'
    - '**/*.md'
  pull_request:
    types:
    - labeled
    paths-ignore:
    - 'docs/**'
    - '**/*.md'

jobs:
  buildAndPush:
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.label.name == 'ok-to-image' }} || ${{ github.event.label.name == 'ok-to-🐳' }} || ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/metalbond
        tags: |
          type=semver,pattern={{version}}
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha
        flavor: |
          latest=${{ github.ref == 'refs/heads/main' }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    # workaround for self-hosted runner
    # https://github.com/mumoshu/actions-runner-controller-ci/commit/e91c8c0f6ca82aa7618010c6d2f417aa46c4a4bf

    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      timeout-minutes: 5
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
        endpoint: builders # self-hosted

    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine version
      id: vars
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          METALBOND_VERSION=$(echo "${{ github.sha }}" | cut -c1-7)
        else
          METALBOND_VERSION=${GITHUB_REF##*/}
        fi
        echo "METALBOND_VERSION=$METALBOND_VERSION" >> $GITHUB_ENV

    - name: Build and push
      timeout-minutes: 40
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          METALBOND_VERSION=${{ env.METALBOND_VERSION }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
