name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: self-hosted
    steps:
      - uses: release-drafter/release-drafter@v5
        id: draft-release
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}