name: release 
on:
  release:
    types:
      - published
  push:
    tags:
    - 'v*'

jobs:
  build_deb:
    uses: ./.github/workflows/build-deb.yml
  publish_github:
    needs: build_deb
    uses: ./.github/workflows/publish-to-github-releases.yml
  publish_gardenlinux_repo:
    needs: build_deb
    uses: ./.github/workflows/publish-to-gardenlinux-repo.yml
    secrets:
      GITLAB_DEPLOY_KEY: ${{ secrets.GITLAB_DEPLOY_KEY }}

